function LegalPage() {
  return (
    <div className="legal-page">
      <header className="legal-header">
        <span className="section-eyebrow">LEGAL</span>
        <h1>Legal & Privacy</h1>
        <p>
          Information about using the SEO Opportunity Analyzer and how
          website data and analytics are handled.
        </p>
      </header>

      <section className="legal-section">
        <h2>Privacy Policy</h2>

        <p>
          <strong>Last updated: August 2026</strong>
        </p>

        <h3>1. Information We Collect</h3>
        <p>
          The SEO Opportunity Analyzer allows you to enter a website URL
          for analysis. The URL you submit is used to perform the requested
          SEO analysis and return the results to you.
        </p>

        <p>
          We do not ask you to create an account or provide personal
          information such as your name or address in order to use the
          analyzer.
        </p>

        <h3>2. Website Analysis</h3>
        <p>
          When you submit a URL, our service may request and analyze publicly
          accessible information from that website, including HTML metadata,
          headings, images, technical files, and social sharing metadata.
        </p>

        <p>
          The analyzer is intended to inspect publicly accessible website
          information. You should only submit URLs that you are authorized
          to analyze.
        </p>

        <h3>3. Analytics and Cookies</h3>
        <p>
          This website may use Google Analytics to understand how visitors
          use the service, such as which pages are visited and how users
          interact with the application.
        </p>

        <p>
          Google Analytics may use cookies or similar technologies to collect
          information about website usage. Depending on your location and
          applicable law, analytics cookies may require your consent before
          they are activated.
        </p>

        <p>
          You can learn more about how Google processes data through
          Google's own privacy documentation.
        </p>

        <h3>4. Third-Party Services</h3>
        <p>
          The service may use third-party providers to operate the website,
          provide analytics, hosting, or other technical functionality.
          These providers may process information in accordance with their
          own privacy policies and applicable agreements.
        </p>

        <h3>5. Data Security</h3>
        <p>
          We take reasonable technical measures to protect the service and
          information processed through it. However, no internet service can
          guarantee absolute security.
        </p>

        <h3>6. Contact</h3>
        <p>
          If you have questions about this Privacy Policy, contact us at{" "}
          <a href="mailto:hello@webxdevelop.com">
            hello@webxdevelop.com
          </a>.
        </p>
      </section>

      <section className="legal-section">
        <h2>Terms of Service</h2>

        <p>
          <strong>Last updated: August 2026</strong>
        </p>

        <h3>1. Use of the Service</h3>
        <p>
          The SEO Opportunity Analyzer provides automated SEO analysis based
          on information that can be retrieved from a submitted website.
          The service is provided for informational purposes.
        </p>

        <h3>2. Acceptable Use</h3>
        <p>
          You agree not to use the service to interfere with, disrupt, or
          attempt to gain unauthorized access to systems or networks. You
          should only submit websites that you are authorized to analyze.
        </p>

        <h3>3. Accuracy of Results</h3>
        <p>
          SEO recommendations generated by the analyzer are automated and
          may not account for every aspect of a website, search engine
          algorithm, or business context.
        </p>

        <p>
          Results should therefore be treated as guidance rather than a
          guarantee of improved search rankings, traffic, or conversions.
        </p>

        <h3>4. Availability</h3>
        <p>
          We may modify, suspend, or discontinue parts of the service at any
          time. We do not guarantee that the service will always be available,
          uninterrupted, or error-free.
        </p>

        <h3>5. Limitation of Liability</h3>
        <p>
          To the extent permitted by applicable law, WebXDevelop is not
          responsible for losses resulting from reliance on automated
          analysis, recommendations, service interruptions, or third-party
          websites analyzed through the service.
        </p>

        <h3>6. Contact</h3>
        <p>
          Questions regarding these Terms can be sent to{" "}
          <a href="mailto:hello@webxdevelop.com">
            hello@webxdevelop.com
          </a>.
        </p>
      </section>
    </div>
  );
}

export default LegalPage;
